### PR TITLE
[Resolves #58] Reuse router between instances when using only static routes

### LINKED ISSUE #58: Re-use router instance between requests
It is still actual https://github.com/yahoo/fluxible-plugin-routr/issues/9

### PR DESCRIPTION
**Pull request by mridgway**

### CODE REVIEW

**Comment by redonkulus** [comment]
Test?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Added.

**Comment by redonkulus** [comment]
:+1:

**Pull request merged**
