### PR TITLE
call done with Error object

### PR DESCRIPTION
**Pull request by pgherveou**
following up with https://github.com/yahoo/fluxible-router/issues/30

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by mridgway** [comment]
Nice catch. Can you also add the `statusCode = 404` to the error object?

**Comment by pgherveou** [comment]
Alright we should do it for the error500 as well then? Do you prefer to dispatch directly the error object or keep it as it is and dispatch an error object with status and message cloned from the dispatched payload?

**Comment by mridgway** [comment]
Yes, we should do both actions. We do not use an `Error` object in the dispatch because it will lose some information when being dehydrated/rehydrated (call stack for instance). This ensures that components are not using data that could be different between client and server.

**Comment by pgherveou** [comment]
It would be nice to add an Error type check in the dispatchr module as well at dev time to catch this kind of errors

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by mridgway** [comment]
Looks good! Thanks!

**Pull request merged**
