### PR TITLE
Removed CHANGE_ROUTE_* from docs.

### PR DESCRIPTION
**Pull request by mjurczyk**
Exchanged CHANGE_ROUTE_* for NAVIGATE_* in the API reference notes.
Issue #26.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by mridgway** [comment]
Thanks @mjurczyk! We just need you to sign the CLA and we'll get this merged.

**Comment by mjurczyk** [comment]
screen shot 2015-05-23 at 13 02 27
 :>

**Comment by redonkulus** [comment]
Thanks!

**Pull request merged**
