### PR TITLE
Add stopPropagation prop option to NavLink

### PR DESCRIPTION
**Pull request by carystanley**
Add stopPropagation prop option to NavLink

@mridgway @redonkulus

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by redonkulus** [comment]
@carystanley can you add a test, coverage decreased.

**Comment by redonkulus** [comment]
:+1:

**Comment by lingyan** [comment]
code looks good.  Could you also add this to doc: https://github.com/yahoo/fluxible-router/blob/master/docs/api/NavLink.md#component-props  Thanks!

**Comment by carystanley** [comment]
Docs updated

**Pull request merged**
